-- Tạo bảng lưu trữ câu hỏi
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  image_url text not null,
  answer text not null,
  is_used boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tự động cập nhật field updated_at (Nâng cao)
create extension if not exists moddatetime schema extensions;
create trigger handle_updated_at before update on public.questions
  for each row execute procedure moddatetime (updated_at);

-- Tạo Bucket trong Supabase Storage để chứa ảnh
insert into storage.buckets (id, name, public) 
values ('question_images', 'question_images', true)
on conflict (id) do nothing;
