-- Tạo bảng lưu trữ thông tin cấu hình Phòng
create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  room_code varchar(6) not null unique,
  admin_name text not null default 'Admin',
  duration int not null default 60,
  question_count int not null default 20,
  status varchar(20) not null default 'waiting', -- waiting, playing, ended
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tự động cập nhật field updated_at (Requires moddatetime extension which was created in questions-schema)
create trigger handle_updated_at_rooms before update on public.rooms
  for each row execute procedure moddatetime (updated_at);
